[is_standard_pdb]
type = "bool"

PDB = """When reading, **is_standard_pdb** is set to ``true`` for residues
defined with a ``ATOM`` record, and ``false`` for atoms defined with an
``HETATM`` record. When writing, **is_standard_pdb** is used to determine
whether to emit an ``HETATM`` or an ``ATOM`` record. If the property is not set,
``HETATM`` is used."""

MMTF = """When reading, **is_standard_pdb** is set to ``false`` when the
``composition_type`` for the group is related to peptide or nucleotide
linkage. See the ``composition_type`` property for residues for more
information. This property is ignored while writing."""

mmCIF = """When reading, **is_standard_pdb** is set to ``true`` when
``_atom_site.group_PDB`` is ``ATOM``, ``false`` when it is ``HETATM``, and is
unset in the absense of this field. When writing, **is_standard_pdb** is used
to determine whether to use ``ATOM`` or ``HETATM`` for ``_atom_site.group_PDB``.
If the property is not set, ``HETATM`` is used."""

[chainname]
type = "string"

PDB = """The **chainname** defines the name assigned to a protein chain by
biologists. It is a single character used to group residues which are linked
together in a crystallographic file where it may not be unique."""

PSF = """The **chainname** is a single character used to group residues which
are linked together. For PSF files, it is taken as the first letter of the
``segname``."""

mmCIF = """The **chainname** defines the name assigned to a protein chain by
biologists. It is a single character used to group residues which are linked
together in a crystallographic file where it may *not* be unique. This name *is*
unique to a given biological assembly, however."""

MMTF = """The **chainname** defines the name assigned to a protein chain by
biologists. It is a single character used to group residues which are linked
together in a crystallographic file where it may *not* be unique. This name *is*
unique to a given biological assembly, however."""

[chainid]
type = "string"

PDB = "For ``PDB`` files, the **chainid** is identical to **chainname**"

PSF = "For ``PSF`` files, the **chainid** is identical to **chainname**"

mmCIF = """The **chainname** defines the name assigned to a protein chain by
biologists. It is is a single character used to group residues which are linked
together in a biologic assembly. It is unique to both the biologic assembly and
the crystal structure."""

MMTF = """The **chainname** defines the name assigned to a protein chain by
biologists. It is is a single character used to group residues which are linked
together in a biologic assembly. It is unique to both the biologic assembly and
the crystal structure."""

[chainindex]
type = "number"

MMTF = """The **chainindex** is a numeric representation of the **chainindex**
and it may be removed in a future release. It will be negative if the residue
is created through a symmetry operation."""

[composition_type]
type = "string"

MMTF = """The **composition_type** defines how residues are chemically bonded.
For example, the majority of proteins consist of ``L-peptide linking``
residues, RNAs consist of ``L-RNA linking``, DNAs consist of ``L-DNA linking``,
and saccharides consist of ``D-saccharide``. See ``chemCompType`` in the mmCIF
dictionary for more details. Since this is a required group property, ``other``
is used when writing unless specified."""

mmCIF = """The **composition_type** defines how residues are chemically bonded.
For example, the majority of proteins consist of ``L-peptide linking``
residues, RNAs consist of ``L-RNA linking``, DNAs consist of ``L-DNA linking``,
and saccharides consist of ``D-saccharide``. See ``chemCompType`` in the mmCIF
dictionary for more details."""

[assembly]
type = "string"

MMTF = """The **assembly** property defines the assignment of biologically
relevent groupings of residues in a crystal structure. For example, the PDBID
``4XUF`` contains two biologically identical copies of the protein FLT3, labled
``bioA`` and ``bioB``, as this protein does not function as a homodimer. The
PDBID ``3OGF``, however, is a homodimer and therefore only contains one
biological assembly with two chains. This property is not used for writing."""

[insertion_code]
type = "string"

PDB = """On reading, this **insertion_code** is set to the insertion code of the
residue. This code is stored as a single character in the PDB file after the
residue id. If this character is a space character, the property is not set. On
writing, this character is stored with the ``ATOM`` or ``HETATM`` record. If the
property is not set, a space character is used."""

[secondary_structure]
type = "string"

PDB = """On reading, the **secondary_structure** is assigned via ``HELIX``,
``SHEET``, and ``TURN`` records. If a residue is listed in a ``SHEET`` record,
then the **secondary_structure** is set to ``extended``. Similarly, the ``TURN``
record will set residues as ``turn``. The ``HELIX`` record is more complex as
the `PDB` standard allows for multiple types of helicies include ``alpha``,
``pi``, and ``3-10`` helicies. This property is not used for writing."""

MMTF = """On reading, the **secondary_structure** is assigned via the
``secStructList`` field in the ``MMTF`` standard. The values assigned match the
descriptions by the *Define Secondary Strucutre of Proteins (DSSP)* algorithm.
Examples include ``extended``, ``alpha helix``, ``pi helix``, ``turn`` and
``coil``. This property is not set for undefined secondary structures and is not
used for writing."""

[segname]
type = "string"
PDB = """``PDB`` files used with CHARM, NAMD and a few other software package
can contain a non-standard *segment* name associated with a residue. If set when
writting a frame, this property is written to the file."""

PSF = """Name of the segment containing this resiude. A segment is typically a
single chain of protein or DNA. Segments may also contain pure solvent or
lipid."""
